/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d821ed83-12cc-4ff6-a736-3cd78a2064b8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MaOjityWO",
    "aws_user_pools_web_client_id": "68kgb4m42a6ob2kp7r6vbnhfvg",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://5bcwnu6ykrfindlxfciwqptsgu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3gdec2usxnaovkdntfjcrcaola",
    "aws_user_files_s3_bucket": "profileapp7673c15329ab4ea7a2004234f51199fa130821-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
